server:
  port: 8081

spring:
  application:
    name: productservice
  datasource:
    url: jdbc:postgresql://localhost:5432/products_db
    username: postgres
    password: postgresql
  jpa:
    show-sql: true
    properties:
      format_sql: true
    defer-datasource-initialization: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    hostname: products